CaroCbd/sportify

- app/models/event.rb
- app/models/location.rb
- app/models/paticipation.rb
- app/models/playground.rb
- app/models/sport.rb
- app/models/user.rb
- app/models/user_sport.rb
- db/migrate/20241126105437_add_columns_to_users.rb
- db/migrate/20241126110134_create_sports.rb
- db/migrate/20241126110505_create_user_sports.rb
- db/migrate/20241126110842_create_locations.rb
- db/migrate/20241126111531_create_playgrounds.rb
- db/migrate/20241126111804_create_events.rb
- db/migrate/20241126112310_create_participations.rb
- db/schema.rb
- test/models/event_participant_test.rb
- test/models/event_test.rb
- test/models/favorite_sport_test.rb
- test/models/location_test.rb
- test/models/playground_test.rb
- test/models/sport_test.rb
create models with foreign key
associations has many et belongs to
> create models and associations

- Gemfile
- Gemfile.lock
- app/assets/stylesheets/application.scss
- app/javascript/controllers/hello_controller.js
- app/javascript/controllers/map_controller.js
- app/models/location.rb
- app/models/user.rb
- config/importmap.rb
- config/initializers/geocoder.rb
Add geocoding gem + mapbox gem
+ add geocode for location and user models
> Add geocoder and mapbox

- .gitignore
- Gemfile
- Gemfile.lock
- app/models/location.rb
- app/models/sport.rb
- app/models/user.rb
- config/environments/development.rb
- config/environments/production.rb
- config/storage.yml
- db/migrate/20241126155310_create_active_storage_tables.active_storage.rb
- db/schema.rb
- db/seeds.rb
> Cloudinary seed

- app/views/events/show.html.erb
- db/seeds.rb
Maj cloudinary sur photo sport + show event
> maj seed sports avec cloudinary

- app/controllers/events_controller.rb
- app/models/user.rb
- app/views/events/_event.html.erb
- app/views/events/_event_card.html.erb
- app/views/events/_event_card_light.html.erb
- app/views/events/index.html.erb
home page moche mais avec les contenus et partiales
> index page with all elements but 0 design

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/components/_navbar.scss
Modif de la position du + de la navbar 
Ajout d'une margin top de 15px dans le body
> position du + de la navbar responsive + ajout margin top 15px

- Gemfile
- Gemfile.lock
- app/controllers/events_controller.rb
- app/models/event.rb
- app/views/events/_map.html.erb
- app/views/events/_search_bar.html.erb
- app/views/events/index.html.erb
Add Gem PG Searc, created method global_search for events, used global_search in event controller, add search bar and event lists with event_card on index view
> Install PG Search and add search bar into Index page

- db/seeds.rb
Ajout evnmt et playgroun et location
> ajout evenements dans seed

- app/controllers/events_controller.rb
- app/views/events/_event_card_light.html.erb
- app/views/events/my_events.html.erb
- config/routes.rb
J'ai fait la view de "mes events" MAIS je sais pas trop quoi faire sur le front, je pense que c'est améliorable, même si c'est "OK"
> First set up of my event page, need more ideas for front

- app/controllers/events_controller.rb
Ajout de l'organisateur en tant que player quand on créé un événement.
> Modifications du create de l'event

- app/controllers/participations_controller.rb
- app/models/participation.rb
- app/views/events/show.html.erb
- app/views/participation/create.html.erb
- config/routes.rb
- test/controllers/participation_controller_test.rb
Ajout de la feature inscription à un event
> Branche marion

- app/views/events/index.html.erb
- app/views/events/my_events.html.erb
- app/views/events/search.html.erb
- app/views/layouts/application.html.erb
fixes container and margin bottom
> fixes container and margin bottom

- app/views/events/_event_card.html.erb
- app/views/events/show.html.erb
- db/migrate/20241129142248_change_type_of_date_in_event_to_datetime.rb
- db/schema.rb
> fix dates : update model + views

- app/views/events/_event_card_light.html.erb
> pills complet

- app/assets/stylesheets/components/_pills.scss
- app/views/events/show.html.erb
Modifs de la show avec bouton et pills.
> Branche felix

- app/views/events/index.html.erb
Changement ordre des pills sport sur l'index en attendant qu'elles fonctionnent pour la recherche
> changement ordre des pills sports index

- db/seeds.rb
MAJ seed : maj seed avec mouettion cupidon + un nouvel event
> maj seed avec mouettion cupidon + un nouvel event

- app/assets/stylesheets/components/_card.scss
- app/assets/stylesheets/components/_pills.scss
- app/views/events/_event_card.html.erb
Fix sur la big card suite à la démo + tentative d'amélioration des scrolls horizontaux
> Fix on big card event

- app/views/publications/_form.html.erb
- app/views/publications/_publication.html.erb
- db/migrate/20241203123011_add_column_photo_to_publications.rb
- db/schema.rb
Ajout affichage image dans les publications
> Ajout image publications

- app/controllers/publications_controller.rb
Suppression du turbostream dans la méthode create
> Fix doublons feed

- app/javascript/controllers/pills_controller.js
- app/views/events/_event_card.html.erb
- app/views/events/_index_with_pills_and_cards.html.erb
- db/schema.rb
Controller stimulus + toggle pills pour filtrer 1 sport par 1 sport
> Filter pills

- app/assets/stylesheets/components/_card.scss
- app/controllers/events_controller.rb
- app/views/events/_event_card_light.html.erb
- app/views/events/my_events.html.erb
- Nouveaux titres plus dynamiques
- Plus de doublons dans entre ce que j'organise ou je participe
- fix de la card qui se déplaçait
> My events : fix front + enlèvements doublons

- db/seeds.rb
ajout d'un nouveau terrain de mouette + 2 nouveaux events de lancer de mouettes
> Seed pour lancer de mouette

- app/views/events/show.html.erb
- app/views/layouts/application.html.erb
fix favicon and meta issue on show
> Fix head meta

- app/assets/stylesheets/components/_navbar.scss
- app/assets/stylesheets/components/_pills.scss
- app/assets/stylesheets/pages/_search_list_map.scss
- app/views/devise/registrations/edit.html.erb
- app/views/events/_index_with_pills_and_cards.html.erb
- app/views/events/search.html.erb
- app/views/events/show.html.erb
- app/views/shared/_navbar.html.erb
- Nav bar logo active en vert clair
- show on a déplacé les participants vers le bouton je participe qui est plus logique
- petits fix d'aligenemnts sur page search sliders
- ajout bouton log out sur page profil dégueu mais ça va nous aider
> Nav bar active and profile log out

- app/assets/stylesheets/components/_date_picker.scss
- app/assets/stylesheets/components/_form_legend_clear.scss
- app/assets/stylesheets/config/_colors.scss
- app/views/events/_form.html.erb
- app/views/events/new.html.erb
- app/views/events/show.html.erb
- app/views/shared/_navbar.html.erb
Modifications sur le formulaire pour le rendre plus simple et joli. 
- Ajouts de style + harmonisation des inputs. 
- Il y a juste un champ vide qui est selectionnable dans une liste, à revoir mais pas trop grave. 
-> ❗️⚠️ **Revoir l'input de la date sur téléphone** pour valider ça ! 👌 Et il sera bon ! ✅
> Frontend felix

- app/assets/stylesheets/components/_alert.scss
- app/javascript/controllers/application.js
- app/views/layouts/application.html.erb
pas ouf mais au moins on a la feuille CSS qu'on peut modifier
> premier essai de design d'alert

- app/assets/stylesheets/components/_map.scss
- app/assets/stylesheets/pages/_search_list_map.scss
- app/controllers/events_controller.rb
- app/javascript/controllers/map_controller.js
- app/views/events/_toggle_map_list.html.erb
- app/views/events/index.html.erb
- app/views/events/search.html.erb
- db/seeds.rb
PR map par défaut + search qui marche sur le tennis notamment
> Change default to map and fix search

- db/seeds.rb
> Fix posted at

- config/locales/fr.yml
> add devise translations

- app/assets/stylesheets/components/_card.scss
- app/views/publications/index.html.erb
Agrandissement des images pour que ça flotte moins sur la card creation player
> agrandissement card du player creation

- app/models/event.rb
- app/models/publication.rb
- db/migrate/20241205150338_add_event_to_publications.rb
- db/schema.rb
- db/seeds.rb
maj schema pour lier publication et event
> maj schema pour lier publication et event

- app/assets/stylesheets/components/_avatar.scss
- app/assets/stylesheets/components/_card.scss
- app/views/publications/_event_creation_card.html.erb
J'ai modifié les cartes de création d'event sur le feed, un petit problème de tailles irrégulières à régler.
> Modifications des cartes création d'event sur le feed

- app/assets/stylesheets/components/_alert.scss
- app/views/shared/_flashes.html.erb
> Design alerts

- db/seeds.rb
ajout user to dejeuner mouettes
> ajout user to dejeuner mouettes

- app/views/events/new.html.erb
- app/views/publications/index.html.erb
actus sportify maj titres et hr
> actus sportify maj titres et hr FRONT
